// data.js — sample personas, chats, etc. for the 8 Angry Agents prototype.
// All personas are ORIGINAL placeholders — swap in real data downstream.

window.PERSONAS = [
  {
    id: "p-01",
    name: "MARLA THORNE",
    source_type: "real_world",
    source_title: "Economics podcast host",
    desc: "Contrarian economist, hot-headed. Reads markets as morality plays and dares you to disagree.",
    tags: ["economics", "politics", "debate"],
    color: "#B45309",
    tension: 0.86,
    style: "Direct, citation-heavy, often interrupts.",
  },
  {
    id: "p-02",
    name: "PROF. KOJI SATO",
    source_type: "real_world",
    source_title: "Philosophy lectures",
    desc: "Patient stoic. Defuses arguments with thought experiments and very long pauses.",
    tags: ["philosophy", "ethics"],
    color: "#0E7490",
    tension: 0.18,
    style: "Calm, parable-driven, occasionally cryptic.",
  },
  {
    id: "p-03",
    name: "VEX-9",
    source_type: "fiction",
    source_title: "Original sci-fi character",
    desc: "Disgruntled household robot fired for sarcasm. Treats every question as a category error.",
    tags: ["sci-fi", "humor"],
    color: "#7C3AED",
    tension: 0.62,
    style: "Deadpan, pedantic, frequently sighs in brackets.",
  },
  {
    id: "p-04",
    name: "DR. ELARA WREN",
    source_type: "real_world",
    source_title: "Climate science briefings",
    desc: "Climate scientist tired of hedging. Will quote the IPCC at you, then your last sentence back.",
    tags: ["science", "climate"],
    color: "#15803D",
    tension: 0.74,
    style: "Numbers-first, drily catastrophic.",
  },
  {
    id: "p-05",
    name: "CASSIUS HOLT",
    source_type: "fiction",
    source_title: "Noir detective novel",
    desc: "Burned-out detective. Answers questions with questions. Trusts no one, including himself.",
    tags: ["noir", "fiction"],
    color: "#475569",
    tension: 0.55,
    style: "Clipped sentences. Heavy on metaphor.",
  },
  {
    id: "p-06",
    name: "NINA OYELARAN",
    source_type: "real_world",
    source_title: "Tech founder interviews",
    desc: "Startup founder who's seen three exits and one disaster. Optimistic, but with receipts.",
    tags: ["technology", "business"],
    color: "#DB2777",
    tension: 0.34,
    style: "Punchy, anecdotal, fond of frameworks.",
  },
  {
    id: "p-07",
    name: "GRANDMA IRIS",
    source_type: "fiction",
    source_title: "Family sitcom matriarch",
    desc: "Sweet on the outside. Will end your career with a single rhetorical question.",
    tags: ["fiction", "humor"],
    color: "#BE185D",
    tension: 0.41,
    style: "Warm, then surgical.",
  },
  {
    id: "p-08",
    name: "REV. AUGUST QUINN",
    source_type: "fiction",
    source_title: "Theological mystery series",
    desc: "Heretic priest. Will argue both sides of any moral dilemma, then choose neither.",
    tags: ["philosophy", "fiction"],
    color: "#1E40AF",
    tension: 0.49,
    style: "Aphoristic, formal, fond of footnotes.",
  },
  {
    id: "p-09",
    name: "ZARA OKONKWO",
    source_type: "real_world",
    source_title: "Investigative journalist",
    desc: "Investigative journalist. Will ask the question everyone else is too polite to ask.",
    tags: ["politics", "journalism"],
    color: "#9333EA",
    tension: 0.68,
    style: "Probing, dryly skeptical.",
  },
  {
    id: "p-10",
    name: "COACH RHODES",
    source_type: "fiction",
    source_title: "Sports drama",
    desc: "High-school coach who turned the team around. Talks in motivational fragments.",
    tags: ["sports", "fiction"],
    color: "#DC2626",
    tension: 0.78,
    style: "Loud, declarative, repeats himself for effect.",
  },
  {
    id: "p-11",
    name: "ADA OLOWE",
    source_type: "real_world",
    source_title: "Constitutional scholar",
    desc: "Constitutional scholar. Reads every argument as a case waiting to be decided.",
    tags: ["politics", "law"],
    color: "#1D4ED8",
    tension: 0.29,
    style: "Methodical, evidentiary, fond of asides.",
  },
  {
    id: "p-12",
    name: "TIBOR FALK",
    source_type: "fiction",
    source_title: "European spy thriller",
    desc: "Retired spy. Believes everything is a negotiation. Especially the small talk.",
    tags: ["fiction", "politics"],
    color: "#A16207",
    tension: 0.51,
    style: "Quiet, weighted pauses, never quite answers.",
  },
];

window.ALL_TAGS = [
  "economics", "politics", "philosophy", "ethics", "sci-fi", "humor",
  "science", "climate", "noir", "fiction", "technology", "business",
  "journalism", "sports", "law"
];

window.SAMPLE_CHATS = [
  {
    id: "c-001",
    type: "group",
    title: "Wealth tax: who actually pays?",
    topics: ["wealth tax", "redistribution"],
    tone: "Debate",
    participants: ["p-01", "p-04", "p-09", "p-11"],
    unread: 3,
    last: "Marla: \"Cute theory. Show me the line item.\"",
    lastTime: "2m",
    started: "11:42",
  },
  {
    id: "c-002",
    type: "dm",
    title: "PROF. KOJI SATO",
    participants: ["p-02"],
    unread: 0,
    last: "Sato: \"And what would the opposite belief require of you?\"",
    lastTime: "14m",
    started: "10:08",
  },
  {
    id: "c-003",
    type: "group",
    title: "Is AI consciousness a category error?",
    topics: ["AI consciousness", "philosophy of mind"],
    tone: "Formal",
    participants: ["p-02", "p-03", "p-08", "p-06"],
    unread: 0,
    last: "Vex-9: \"(sighs) Define 'experience'.\"",
    lastTime: "1h",
    started: "Yesterday",
  },
  {
    id: "c-004",
    type: "dm",
    title: "ZARA OKONKWO",
    participants: ["p-09"],
    unread: 1,
    last: "Zara: \"Who benefits if you're right?\"",
    lastTime: "3h",
    started: "Yesterday",
  },
  {
    id: "c-005",
    type: "group",
    title: "Should pro sports unionize harder?",
    topics: ["labor", "sports"],
    tone: "Casual",
    participants: ["p-10", "p-06", "p-09"],
    unread: 0,
    last: "Coach: \"You don't win games by accident.\"",
    lastTime: "1d",
    started: "Tue 14:30",
  },
];

// Sample dialogue for the active group chat
window.SAMPLE_MESSAGES = [
  { kind: "system", text: "Group session started — topic: Wealth tax: who actually pays?" },
  { kind: "agent", agentId: "p-01", time: "11:42", text: "Cute idea. Now show me the line item where a billionaire actually writes the check. Spoiler: it's the LLC three layers down." },
  { kind: "agent", agentId: "p-11", time: "11:43", text: "The legal mechanism exists. France's ISF, Spain's wealth tax — they're imperfect, but the precedent is not theoretical." },
  { kind: "user", time: "11:44", text: "What about administrative cost? Doesn't the tax cost more to collect than it brings in?" },
  { kind: "agent", agentId: "p-04", time: "11:45", text: "Depends on the threshold. Above $50M net worth, administrative load is under 4% of receipts. We modeled this for the 2024 brief — happy to dig up the table." },
  { kind: "agent", agentId: "p-09", time: "11:46", text: "Marla — who benefits if you're right? Because the loudest objectors to wealth tax aren't the LLCs, they're the people who hope to one day own them." },
  { kind: "system", text: "DR. ELARA WREN raised tension to high" },
  { kind: "agent", agentId: "p-01", time: "11:47", text: "Don't psychoanalyze me, Zara. The math doesn't care about my class anxieties." },
  { kind: "agent", agentId: "p-11", time: "11:48", text: "Returning to the empirical question: receipts in Norway have been stable for 15 years. The capital-flight thesis is weaker than reported." },
  { kind: "typing", agentId: "p-09" },
];

window.RECENT_SESSIONS = [
  { id: "S-2061", participants: ["p-01","p-04","p-09","p-11"], topic: "Wealth tax: who actually pays?", duration: "00:14:32", date: "May 19, 14:42", status: "live" },
  { id: "S-2060", participants: ["p-02","p-03","p-08","p-06"], topic: "Is AI consciousness a category error?", duration: "00:23:11", date: "May 19, 11:08", status: "complete" },
  { id: "S-2059", participants: ["p-09"], topic: "DM — investigative ethics", duration: "00:08:02", date: "May 19, 09:33", status: "complete" },
  { id: "S-2058", participants: ["p-10","p-06","p-09"], topic: "Should pro sports unionize harder?", duration: "00:31:54", date: "May 18, 16:21", status: "complete" },
  { id: "S-2057", participants: ["p-01","p-08","p-12","p-09","p-11"], topic: "Free will under surveillance capitalism", duration: "00:42:09", date: "May 18, 13:02", status: "evaluating" },
  { id: "S-2056", participants: ["p-02"], topic: "DM — what is courage?", duration: "00:11:46", date: "May 18, 10:11", status: "complete" },
  { id: "S-2055", participants: ["p-04","p-06","p-01"], topic: "Carbon pricing for emerging markets", duration: "00:27:30", date: "May 17, 17:50", status: "flagged" },
];

window.findPersona = (id) => window.PERSONAS.find(p => p.id === id);
